# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# lane :beta do
#   increment_build_number(xcodeproj: "SodaPopcorn.xcodeproj")
#   build_app(scheme: "SodaPopcorn")
#   upload_to_testflight
# end

# lane :build do
#   build_app(scheme: "SodaPopcorn")
#   increment_build_number(xcodeproj: "SodaPopcorn.xcodeproj")
# end

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     increment_build_number(xcodeproj: "SodaPopcorn.xcodeproj")
#     build_app(scheme: "SodaPopcorn")
#     upload_to_testflight
#   end
# end
